### ISSUE TITLE
pygobject installation fails

### ISSUE THREAD

**Issue by stormtroopa** [troyxmccall/homebrew-mopidy#1]
It doesn't work on my machine. I get a 404 for the pygobject:
==> Reinstalling troyxmccall/mopidy/pygobject3@2 ==> Downloading https://homebrew.bintray.com/bottles-mopidy/pygobject3@2-3.34.0 curl: (22) The requested URL returned error: 404 Not Found Error: Failed to download resource "pygobject3@2" Warning: Bottle installation failed: building from source

Any ideas whats wrong here?

**Comment by troyxmccall** [comment]
@stormtroopa building from source is expected behavior here, there are no bottles since this is a workaround, can you post what follows after "building from source"

**Comment by stormtroopa** [comment]
Hey troyxmccall,
thanks for helping out!

`Warning: troyxmccall/mopidy/gst-python@2 1.16.0 is already installed and up-to-date
To reinstall 1.16.0, run `brew reinstall gst-python@2`
Warning: troyxmccall/mopidy/pygobject3@2 3.34.0 is already installed, it's just not linked
You can use `brew link pygobject3@2` to link this version.
Warning: troyxmccall/mopidy/mopidy 2.2.2 is already installed and up-to-date
To reinstall 2.2.2, run `brew reinstall mopidy`
Warning: troyxmccall/mopidy/mopidy-spotify 3.1.0_1 is already installed and up-to-date
To reinstall 3.1.0_1, run `brew reinstall mopidy-spotify`

I linked as pygobject as recommended.

starting mopidy generates another fault: 
`Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources`

**Comment by troyxmccall** [comment]
@stormtroopa two things

run: `sudo pip install setuptools`

and then `brew doctor`

and give me the output of both

**Comment by stormtroopa** [comment]
running pip brings this message:
`File "/usr/local/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources`

I used pip3 instead, which worked.
`brew doctor` resulted in some broken symlink warnings which I fixed right away.

Running brew doctor again shows following warnings: 
`Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/SUVMMFaker.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/js_native_api.h`

and hundred more header-files all in the same directory.

**Comment by stormtroopa** [comment]
I also tried the installation on my other machine. I get a meson error message there:
`==> meson --prefix=/usr/local/Cellar/pygobject3@2/3.34.0 -Dpycairo=true -Dpytho
Last 15 lines from /Users/stormtroopa/Library/Logs/Homebrew/pygobject3@2/01.meson:
2019-11-03 23:46:33 +0100

meson
--prefix=/usr/local/Cellar/pygobject3@2/3.34.0
-Dpycairo=true
-Dpython=python2.7
..

Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.52.0/libexec/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'`

**Comment by troyxmccall** [comment]
hrm, this seems to be an issue with pip/python as a whole for you

try both of these

```

# virtualenv
python -m pip install --upgrade pip
pip install --upgrade setuptools

# system level
sudo python -m pip install --upgrade pip
sudo pip install --upgrade setuptools
```

**Comment by stormtroopa** [comment]
Thank you troyxmccall for pointing me towards pip.
The commands above didn't run since pip could not be found. Donno why pip suddenly disappeared. I did the following to solve the problem:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```
I am so happy mopidy runs again.

Thanks again for helping out so quickly.

I am looking forward to the mopidy / python3 release and hope it gets more stable then.
